version: '2'

volumes:
    downloads:
    transmission-config:

services:
    static-server:
        build: static-server
        volumes_from:
            - transmission:rw
        ports:
            - 80:80
    static-server2:
	build: static-server
        volumes_from:
           - transmission:rw
        ports:
           - 81:81
